### ISSUE TITLE
Geoscience bug

### ISSUE THREAD

**Issue by bjjeong2003** [rolandhill/geoscience#15]
Whenver I execute desurvey hole, I am faced with the message the collar 3D and Collar_Desurvey file were not made.

**Comment by rolandhill** [comment]
Usually this type of error is associated with the path name. Are you trying
to write to a local drive rather than a network share? Also, non-english
characters can cause issues. The first thing I would do is try it again
using a simple, english character path on a local drive and see if it works.

Regards,
Roland

**Comment by bjjeong2003** [comment]
Thank you so much Mr.Hill!
I got success.

2023년 3월 9일 (목) 오후 11:35, Roland Hill ***@***.***>님이 작성:

> Usually this type of error is associated with the path name. Are you trying
> to write to a local drive rather than a network share? Also, non-english
> characters can cause issues. The first thing I would do is try it again
> using a simple, english character path on a local drive and see if it
> works.
>
> Regards,
> Roland
>
>
